# Generated by Django 5.0.6 on 2024-06-24 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('student_index_number', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_contact', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('admission', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='bank_statement/')),
                ('status', models.CharField(default='Not Registered', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.FileField(upload_to='bank_statements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='student_registration_portal.student')),
            ],
        ),
    ]
