# Generated by Django 5.0.6 on 2024-06-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration_portal', '0002_alter_student_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='next_of_kin_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_index_number',
            field=models.CharField(max_length=50),
        ),
    ]
