# Generated by Django 5.0.6 on 2024-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration_portal', '0003_alter_student_contact_no_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(max_length=10),
        ),
    ]
